name: build-scan-and-publish

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ASSUMABLE_ROLE: ${{ secrets.AWS_ASSUMABLE_ROLE }}
  AWS_REGION: ${{ secrets.AWS_REGION }}  

permissions:
  id-token: write
  contents: read

jobs:
  build-and-scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ASSUMABLE_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 1200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        run: |
          docker build . -t distroless-nginx:${{ github.sha }}

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3

      - name: Scan image with Trivy 
        run: |
          trivy image distroless-nginx:${{ github.sha }}

      - name: Tag image and push to ECR
        run: | 
          docker tag distroless-nginx:${{ github.sha }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/distroless-nginx:latest
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/distroless-nginx:latest
