name: publish-distroless-nginx-image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY_IMAGE: ${{ secrets.SCALEWAY_REGISTRY_ENDPOINT }}/distroless-nginx

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["", "debug"]
        platform: ["linux/amd64", "linux/arm64"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=match,enable=true,prefix=,suffix=${{ (matrix.tag == '' && matrix.tag) ||  format('-{0}', matrix.tag) }},onlatest=true,pattern=v(\d+.\d+.\d+),group=1
            type=match,enable=true,prefix=,suffix=${{ (matrix.tag == '' && matrix.tag) ||  format('-{0}', matrix.tag) }},onlatest=true,pattern=v(\d+.\d+),group=1
            type=match,enable=true,prefix=,suffix=${{ (matrix.tag == '' && matrix.tag) ||  format('-{0}', matrix.tag) }},onlatest=true,pattern=v(\d+),group=1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SCALEWAY_REGISTRY_ENDPOINT }}
          username: ${{ secrets.SCALEWAY_REGISTRY_USERNAME }}
          password: ${{ secrets.SCALEWAY_REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile${{ (matrix.tag == '' && matrix.tag) ||  format('.{0}', matrix.tag) }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}